# Generated by Django 5.1.6 on 2025-04-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
