# Generated by Django 5.1.6 on 2025-04-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurrence_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
